import { Injectable } from '@angular/core';
import { Actions, concatLatestFrom, createEffect, ofType } from '@ngrx/effects';
import { Store } from '@ngrx/store';
import { catchError, map, mergeMap, observeOn, switchMap, tap } from 'rxjs/operators';
import { AppStoreService } from '../services/app-store.service';
import { UsersService } from '../pages/components/users-page/services/users-page.service';
import { AppActions, getUserGridDataSuccess, getUserRepositoriesListSuccess } from './app.actions';
import { RepositoriesService } from '../pages/components/repositories-page/services/repositories-page.service';
import { IUserGridItem } from '../pages/components/users-page/models/users-page.iterfaces';

@Injectable({
  providedIn: 'root',
})
@Injectable()
export class AppEffects {
  constructor(
    private readonly _actions$: Actions,
    private readonly _storeService: AppStoreService,
    private readonly _usersService: UsersService,
    private readonly _store: Store,
    private readonly _repositoriesService: RepositoriesService,
  ) {}

  fetchUsersGridData$ = createEffect(() =>
    this._actions$.pipe(
      ofType(AppActions.FetchUserGridData),
      switchMap(({ page, per_page }) =>
        this._usersService.getUsers(page, per_page)
      ),
      map(({ items }) => {
        
        const res = items?.map((p: { login: any; id: any; type: any; url: any; score: any; avatar_url: any; isFavorite: boolean }) => <any>
        {
          login: p.login,
          id: p.id,
          url: p.url,
          type: p.type,
          score: p.score,
          avatarUrl: p.avatar_url,
          isFavorite: false
        });

        return getUserGridDataSuccess({ data: res });
      })
    )
  );

  fetchUsersGridDataWithTotal$ = createEffect(() =>
    this._actions$.pipe(
      ofType(AppActions.FetchUserGridDataWithTotal),
      switchMap(({ page, per_page }) =>
        this._usersService.getUsers(page, per_page)
      ),
      map(({ items, total_count }) => {
        
        const res = items?.map((p: { login: any; id: any; type: any; url: any; score: any; avatar_url: any; isFavorite: boolean }) => <IUserGridItem>
        {
          login: p.login,
          id: p.id,
          url: p.url,
          type: p.type,
          score: p.score,
          avatarUrl: p.avatar_url,
          isFavorite: false
        });

        return getUserGridDataSuccess({ data: res, total: total_count });
      })
    )
  );

  fetchUserRepositoriesList$ = createEffect(() =>
    this._actions$.pipe(
      ofType(AppActions.FetchUserRepositoriesList),
      switchMap(({ login, page, per_page }) =>
        this._repositoriesService.getRepositories(login, page, per_page)
      ),
      map((res) => {
        
        // const res = items;

        return getUserRepositoriesListSuccess({ data: res });
      }),
      catchError(() => {
        console.log('catchError');
        
        const list = [
          {
            "id": 236731722,
            "node_id": "MDEwOlJlcG9zaXRvcnkyMzY3MzE3MjI=",
            "name": "4DViewsTest",
            "full_name": "keijiro/4DViewsTest",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/4DViewsTest",
            "description": "4DViews volumetric video + Unity",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/4DViewsTest",
            "forks_url": "https://api.github.com/repos/keijiro/4DViewsTest/forks",
            "keys_url": "https://api.github.com/repos/keijiro/4DViewsTest/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/4DViewsTest/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/4DViewsTest/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/4DViewsTest/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/4DViewsTest/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/4DViewsTest/events",
            "assignees_url": "https://api.github.com/repos/keijiro/4DViewsTest/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/4DViewsTest/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/4DViewsTest/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/4DViewsTest/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/4DViewsTest/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/4DViewsTest/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/4DViewsTest/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/4DViewsTest/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/4DViewsTest/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/4DViewsTest/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/4DViewsTest/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/4DViewsTest/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/4DViewsTest/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/4DViewsTest/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/4DViewsTest/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/4DViewsTest/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/4DViewsTest/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/4DViewsTest/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/4DViewsTest/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/4DViewsTest/merges",
            "archive_url": "https://api.github.com/repos/keijiro/4DViewsTest/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/4DViewsTest/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/4DViewsTest/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/4DViewsTest/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/4DViewsTest/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/4DViewsTest/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/4DViewsTest/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/4DViewsTest/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/4DViewsTest/deployments",
            "created_at": "2020-01-28T12:36:56Z",
            "updated_at": "2023-03-31T11:08:50Z",
            "pushed_at": "2020-03-05T14:05:20Z",
            "git_url": "git://github.com/keijiro/4DViewsTest.git",
            "ssh_url": "git@github.com:keijiro/4DViewsTest.git",
            "clone_url": "https://github.com/keijiro/4DViewsTest.git",
            "svn_url": "https://github.com/keijiro/4DViewsTest",
            "homepage": "",
            "size": 196,
            "stargazers_count": 92,
            "watchers_count": 92,
            "language": "C#",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 11,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
              "unity",
              "unity3d",
              "vfx",
              "volumetric-video"
            ],
            "visibility": "public",
            "forks": 11,
            "open_issues": 0,
            "watchers": 92,
            "default_branch": "master"
          },
          {
            "id": 269894989,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNjk4OTQ5ODk=",
            "name": "4DViewsTest2",
            "full_name": "keijiro/4DViewsTest2",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/4DViewsTest2",
            "description": "4DViews volumetric video with Unity VFX Graph",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/4DViewsTest2",
            "forks_url": "https://api.github.com/repos/keijiro/4DViewsTest2/forks",
            "keys_url": "https://api.github.com/repos/keijiro/4DViewsTest2/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/4DViewsTest2/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/4DViewsTest2/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/4DViewsTest2/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/4DViewsTest2/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/4DViewsTest2/events",
            "assignees_url": "https://api.github.com/repos/keijiro/4DViewsTest2/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/4DViewsTest2/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/4DViewsTest2/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/4DViewsTest2/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/4DViewsTest2/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/4DViewsTest2/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/4DViewsTest2/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/4DViewsTest2/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/4DViewsTest2/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/4DViewsTest2/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/4DViewsTest2/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/4DViewsTest2/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/4DViewsTest2/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/4DViewsTest2/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/4DViewsTest2/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/4DViewsTest2/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/4DViewsTest2/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/4DViewsTest2/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/4DViewsTest2/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/4DViewsTest2/merges",
            "archive_url": "https://api.github.com/repos/keijiro/4DViewsTest2/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/4DViewsTest2/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/4DViewsTest2/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/4DViewsTest2/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/4DViewsTest2/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/4DViewsTest2/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/4DViewsTest2/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/4DViewsTest2/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/4DViewsTest2/deployments",
            "created_at": "2020-06-06T06:47:24Z",
            "updated_at": "2023-04-11T11:33:10Z",
            "pushed_at": "2020-06-19T15:31:58Z",
            "git_url": "git://github.com/keijiro/4DViewsTest2.git",
            "ssh_url": "git@github.com:keijiro/4DViewsTest2.git",
            "clone_url": "https://github.com/keijiro/4DViewsTest2.git",
            "svn_url": "https://github.com/keijiro/4DViewsTest2",
            "homepage": "",
            "size": 658,
            "stargazers_count": 68,
            "watchers_count": 68,
            "language": "HLSL",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 11,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
              "4dviews",
              "unity",
              "unity3d",
              "vfx",
              "vfxgraph"
            ],
            "visibility": "public",
            "forks": 11,
            "open_issues": 0,
            "watchers": 68,
            "default_branch": "master"
          },
          {
            "id": 278831241,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNzg4MzEyNDE=",
            "name": "4DViewsTest3",
            "full_name": "keijiro/4DViewsTest3",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/4DViewsTest3",
            "description": "4DViews volumetric video with Unity DXR realtime ray tracing",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/4DViewsTest3",
            "forks_url": "https://api.github.com/repos/keijiro/4DViewsTest3/forks",
            "keys_url": "https://api.github.com/repos/keijiro/4DViewsTest3/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/4DViewsTest3/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/4DViewsTest3/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/4DViewsTest3/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/4DViewsTest3/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/4DViewsTest3/events",
            "assignees_url": "https://api.github.com/repos/keijiro/4DViewsTest3/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/4DViewsTest3/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/4DViewsTest3/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/4DViewsTest3/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/4DViewsTest3/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/4DViewsTest3/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/4DViewsTest3/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/4DViewsTest3/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/4DViewsTest3/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/4DViewsTest3/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/4DViewsTest3/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/4DViewsTest3/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/4DViewsTest3/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/4DViewsTest3/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/4DViewsTest3/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/4DViewsTest3/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/4DViewsTest3/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/4DViewsTest3/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/4DViewsTest3/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/4DViewsTest3/merges",
            "archive_url": "https://api.github.com/repos/keijiro/4DViewsTest3/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/4DViewsTest3/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/4DViewsTest3/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/4DViewsTest3/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/4DViewsTest3/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/4DViewsTest3/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/4DViewsTest3/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/4DViewsTest3/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/4DViewsTest3/deployments",
            "created_at": "2020-07-11T09:37:23Z",
            "updated_at": "2023-05-13T10:23:54Z",
            "pushed_at": "2020-08-02T07:43:09Z",
            "git_url": "git://github.com/keijiro/4DViewsTest3.git",
            "ssh_url": "git@github.com:keijiro/4DViewsTest3.git",
            "clone_url": "https://github.com/keijiro/4DViewsTest3.git",
            "svn_url": "https://github.com/keijiro/4DViewsTest3",
            "homepage": "",
            "size": 14863,
            "stargazers_count": 64,
            "watchers_count": 64,
            "language": "C#",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 10,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
              "dxr",
              "graphics",
              "raytracing",
              "unity",
              "unity3d"
            ],
            "visibility": "public",
            "forks": 10,
            "open_issues": 0,
            "watchers": 64,
            "default_branch": "master"
          },
          {
            "id": 40172020,
            "node_id": "MDEwOlJlcG9zaXRvcnk0MDE3MjAyMA==",
            "name": "ABCachingTest",
            "full_name": "keijiro/ABCachingTest",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/ABCachingTest",
            "description": "Asset bundle caching behavior test.",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/ABCachingTest",
            "forks_url": "https://api.github.com/repos/keijiro/ABCachingTest/forks",
            "keys_url": "https://api.github.com/repos/keijiro/ABCachingTest/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/ABCachingTest/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/ABCachingTest/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/ABCachingTest/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/ABCachingTest/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/ABCachingTest/events",
            "assignees_url": "https://api.github.com/repos/keijiro/ABCachingTest/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/ABCachingTest/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/ABCachingTest/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/ABCachingTest/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/ABCachingTest/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/ABCachingTest/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/ABCachingTest/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/ABCachingTest/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/ABCachingTest/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/ABCachingTest/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/ABCachingTest/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/ABCachingTest/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/ABCachingTest/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/ABCachingTest/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/ABCachingTest/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/ABCachingTest/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/ABCachingTest/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/ABCachingTest/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/ABCachingTest/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/ABCachingTest/merges",
            "archive_url": "https://api.github.com/repos/keijiro/ABCachingTest/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/ABCachingTest/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/ABCachingTest/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/ABCachingTest/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/ABCachingTest/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/ABCachingTest/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/ABCachingTest/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/ABCachingTest/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/ABCachingTest/deployments",
            "created_at": "2015-08-04T08:15:15Z",
            "updated_at": "2021-11-01T23:01:05Z",
            "pushed_at": "2015-08-04T08:28:17Z",
            "git_url": "git://github.com/keijiro/ABCachingTest.git",
            "ssh_url": "git@github.com:keijiro/ABCachingTest.git",
            "clone_url": "https://github.com/keijiro/ABCachingTest.git",
            "svn_url": "https://github.com/keijiro/ABCachingTest",
            "homepage": null,
            "size": 1980,
            "stargazers_count": 2,
            "watchers_count": 2,
            "language": "C#",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 2,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 2,
            "open_issues": 0,
            "watchers": 2,
            "default_branch": "master"
          },
          {
            "id": 269525012,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNjk1MjUwMTI=",
            "name": "Abcvfx",
            "full_name": "keijiro/Abcvfx",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/Abcvfx",
            "description": "A Unity package that allows using an Alembic animation as a VFX source",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/Abcvfx",
            "forks_url": "https://api.github.com/repos/keijiro/Abcvfx/forks",
            "keys_url": "https://api.github.com/repos/keijiro/Abcvfx/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/Abcvfx/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/Abcvfx/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/Abcvfx/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/Abcvfx/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/Abcvfx/events",
            "assignees_url": "https://api.github.com/repos/keijiro/Abcvfx/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/Abcvfx/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/Abcvfx/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/Abcvfx/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/Abcvfx/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/Abcvfx/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/Abcvfx/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/Abcvfx/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/Abcvfx/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/Abcvfx/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/Abcvfx/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/Abcvfx/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/Abcvfx/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/Abcvfx/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/Abcvfx/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/Abcvfx/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/Abcvfx/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/Abcvfx/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/Abcvfx/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/Abcvfx/merges",
            "archive_url": "https://api.github.com/repos/keijiro/Abcvfx/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/Abcvfx/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/Abcvfx/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/Abcvfx/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/Abcvfx/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/Abcvfx/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/Abcvfx/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/Abcvfx/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/Abcvfx/deployments",
            "created_at": "2020-06-05T03:47:31Z",
            "updated_at": "2023-04-11T19:43:01Z",
            "pushed_at": "2020-07-11T14:48:46Z",
            "git_url": "git://github.com/keijiro/Abcvfx.git",
            "ssh_url": "git@github.com:keijiro/Abcvfx.git",
            "clone_url": "https://github.com/keijiro/Abcvfx.git",
            "svn_url": "https://github.com/keijiro/Abcvfx",
            "homepage": "",
            "size": 1799,
            "stargazers_count": 70,
            "watchers_count": 70,
            "language": "C#",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 8,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
              "alembic",
              "unity",
              "unity3d",
              "vfx",
              "vfxgraph"
            ],
            "visibility": "public",
            "forks": 8,
            "open_issues": 1,
            "watchers": 70,
            "default_branch": "master"
          },
          {
            "id": 11871893,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMTg3MTg5Mw==",
            "name": "ableton-sketches",
            "full_name": "keijiro/ableton-sketches",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/ableton-sketches",
            "description": "Sketches made with Ableton Live",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/ableton-sketches",
            "forks_url": "https://api.github.com/repos/keijiro/ableton-sketches/forks",
            "keys_url": "https://api.github.com/repos/keijiro/ableton-sketches/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/ableton-sketches/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/ableton-sketches/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/ableton-sketches/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/ableton-sketches/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/ableton-sketches/events",
            "assignees_url": "https://api.github.com/repos/keijiro/ableton-sketches/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/ableton-sketches/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/ableton-sketches/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/ableton-sketches/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/ableton-sketches/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/ableton-sketches/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/ableton-sketches/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/ableton-sketches/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/ableton-sketches/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/ableton-sketches/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/ableton-sketches/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/ableton-sketches/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/ableton-sketches/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/ableton-sketches/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/ableton-sketches/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/ableton-sketches/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/ableton-sketches/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/ableton-sketches/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/ableton-sketches/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/ableton-sketches/merges",
            "archive_url": "https://api.github.com/repos/keijiro/ableton-sketches/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/ableton-sketches/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/ableton-sketches/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/ableton-sketches/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/ableton-sketches/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/ableton-sketches/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/ableton-sketches/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/ableton-sketches/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/ableton-sketches/deployments",
            "created_at": "2013-08-04T01:16:53Z",
            "updated_at": "2018-04-20T21:49:08Z",
            "pushed_at": "2013-12-19T10:15:10Z",
            "git_url": "git://github.com/keijiro/ableton-sketches.git",
            "ssh_url": "git@github.com:keijiro/ableton-sketches.git",
            "clone_url": "https://github.com/keijiro/ableton-sketches.git",
            "svn_url": "https://github.com/keijiro/ableton-sketches",
            "homepage": null,
            "size": 3560,
            "stargazers_count": 3,
            "watchers_count": 3,
            "language": null,
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 2,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 2,
            "open_issues": 0,
            "watchers": 3,
            "default_branch": "master"
          },
          {
            "id": 1816653,
            "node_id": "MDEwOlJlcG9zaXRvcnkxODE2NjUz",
            "name": "achilles",
            "full_name": "keijiro/achilles",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/achilles",
            "description": "Unity example project.",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/achilles",
            "forks_url": "https://api.github.com/repos/keijiro/achilles/forks",
            "keys_url": "https://api.github.com/repos/keijiro/achilles/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/achilles/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/achilles/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/achilles/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/achilles/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/achilles/events",
            "assignees_url": "https://api.github.com/repos/keijiro/achilles/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/achilles/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/achilles/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/achilles/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/achilles/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/achilles/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/achilles/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/achilles/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/achilles/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/achilles/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/achilles/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/achilles/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/achilles/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/achilles/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/achilles/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/achilles/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/achilles/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/achilles/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/achilles/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/achilles/merges",
            "archive_url": "https://api.github.com/repos/keijiro/achilles/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/achilles/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/achilles/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/achilles/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/achilles/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/achilles/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/achilles/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/achilles/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/achilles/deployments",
            "created_at": "2011-05-29T06:40:35Z",
            "updated_at": "2019-03-26T06:12:19Z",
            "pushed_at": "2011-12-22T17:31:39Z",
            "git_url": "git://github.com/keijiro/achilles.git",
            "ssh_url": "git@github.com:keijiro/achilles.git",
            "clone_url": "https://github.com/keijiro/achilles.git",
            "svn_url": "https://github.com/keijiro/achilles",
            "homepage": "http://keijiro.github.com/achilles",
            "size": 10158,
            "stargazers_count": 4,
            "watchers_count": 4,
            "language": "JavaScript",
            "has_issues": false,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": true,
            "has_discussions": false,
            "forks_count": 1,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 0,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 1,
            "open_issues": 0,
            "watchers": 4,
            "default_branch": "master"
          },
          {
            "id": 109957823,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMDk5NTc4MjM=",
            "name": "AdamPlaneReflection",
            "full_name": "keijiro/AdamPlaneReflection",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/AdamPlaneReflection",
            "description": "Planar reflection effect from the Adam Interior Environment package.",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/AdamPlaneReflection",
            "forks_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/forks",
            "keys_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/events",
            "assignees_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/merges",
            "archive_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/AdamPlaneReflection/deployments",
            "created_at": "2017-11-08T09:53:39Z",
            "updated_at": "2023-05-11T03:21:55Z",
            "pushed_at": "2017-11-08T14:33:04Z",
            "git_url": "git://github.com/keijiro/AdamPlaneReflection.git",
            "ssh_url": "git@github.com:keijiro/AdamPlaneReflection.git",
            "clone_url": "https://github.com/keijiro/AdamPlaneReflection.git",
            "svn_url": "https://github.com/keijiro/AdamPlaneReflection",
            "homepage": "https://www.assetstore.unity3d.com/en/#!/content/74965",
            "size": 15821,
            "stargazers_count": 101,
            "watchers_count": 101,
            "language": "C#",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 12,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 2,
            "license": {
              "key": "mit",
              "name": "MIT License",
              "spdx_id": "MIT",
              "url": "https://api.github.com/licenses/mit",
              "node_id": "MDc6TGljZW5zZTEz"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
              "shader",
              "unity",
              "unity3d"
            ],
            "visibility": "public",
            "forks": 12,
            "open_issues": 2,
            "watchers": 101,
            "default_branch": "master"
          },
          {
            "id": 615651912,
            "node_id": "R_kgDOJLIaSA",
            "name": "AICommand",
            "full_name": "keijiro/AICommand",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/AICommand",
            "description": "ChatGPT integration with Unity Editor",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/AICommand",
            "forks_url": "https://api.github.com/repos/keijiro/AICommand/forks",
            "keys_url": "https://api.github.com/repos/keijiro/AICommand/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/AICommand/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/AICommand/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/AICommand/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/AICommand/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/AICommand/events",
            "assignees_url": "https://api.github.com/repos/keijiro/AICommand/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/AICommand/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/AICommand/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/AICommand/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/AICommand/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/AICommand/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/AICommand/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/AICommand/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/AICommand/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/AICommand/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/AICommand/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/AICommand/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/AICommand/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/AICommand/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/AICommand/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/AICommand/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/AICommand/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/AICommand/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/AICommand/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/AICommand/merges",
            "archive_url": "https://api.github.com/repos/keijiro/AICommand/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/AICommand/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/AICommand/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/AICommand/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/AICommand/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/AICommand/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/AICommand/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/AICommand/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/AICommand/deployments",
            "created_at": "2023-03-18T09:23:23Z",
            "updated_at": "2023-05-16T14:01:32Z",
            "pushed_at": "2023-03-28T05:17:48Z",
            "git_url": "git://github.com/keijiro/AICommand.git",
            "ssh_url": "git@github.com:keijiro/AICommand.git",
            "clone_url": "https://github.com/keijiro/AICommand.git",
            "svn_url": "https://github.com/keijiro/AICommand",
            "homepage": "",
            "size": 33,
            "stargazers_count": 3497,
            "watchers_count": 3497,
            "language": "C#",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 388,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 6,
            "license": {
              "key": "unlicense",
              "name": "The Unlicense",
              "spdx_id": "Unlicense",
              "url": "https://api.github.com/licenses/unlicense",
              "node_id": "MDc6TGljZW5zZTE1"
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 388,
            "open_issues": 6,
            "watchers": 3497,
            "default_branch": "main"
          },
          {
            "id": 609844970,
            "node_id": "R_kgDOJFl-6g",
            "name": "AIShader",
            "full_name": "keijiro/AIShader",
            "private": false,
            "owner": {
              "login": "keijiro",
              "id": 343936,
              "node_id": "MDQ6VXNlcjM0MzkzNg==",
              "avatar_url": "https://avatars.githubusercontent.com/u/343936?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/keijiro",
              "html_url": "https://github.com/keijiro",
              "followers_url": "https://api.github.com/users/keijiro/followers",
              "following_url": "https://api.github.com/users/keijiro/following{/other_user}",
              "gists_url": "https://api.github.com/users/keijiro/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/keijiro/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/keijiro/subscriptions",
              "organizations_url": "https://api.github.com/users/keijiro/orgs",
              "repos_url": "https://api.github.com/users/keijiro/repos",
              "events_url": "https://api.github.com/users/keijiro/events{/privacy}",
              "received_events_url": "https://api.github.com/users/keijiro/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/keijiro/AIShader",
            "description": "ChatGPT-powered shader generator for Unity",
            "fork": false,
            "url": "https://api.github.com/repos/keijiro/AIShader",
            "forks_url": "https://api.github.com/repos/keijiro/AIShader/forks",
            "keys_url": "https://api.github.com/repos/keijiro/AIShader/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/keijiro/AIShader/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/keijiro/AIShader/teams",
            "hooks_url": "https://api.github.com/repos/keijiro/AIShader/hooks",
            "issue_events_url": "https://api.github.com/repos/keijiro/AIShader/issues/events{/number}",
            "events_url": "https://api.github.com/repos/keijiro/AIShader/events",
            "assignees_url": "https://api.github.com/repos/keijiro/AIShader/assignees{/user}",
            "branches_url": "https://api.github.com/repos/keijiro/AIShader/branches{/branch}",
            "tags_url": "https://api.github.com/repos/keijiro/AIShader/tags",
            "blobs_url": "https://api.github.com/repos/keijiro/AIShader/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/keijiro/AIShader/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/keijiro/AIShader/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/keijiro/AIShader/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/keijiro/AIShader/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/keijiro/AIShader/languages",
            "stargazers_url": "https://api.github.com/repos/keijiro/AIShader/stargazers",
            "contributors_url": "https://api.github.com/repos/keijiro/AIShader/contributors",
            "subscribers_url": "https://api.github.com/repos/keijiro/AIShader/subscribers",
            "subscription_url": "https://api.github.com/repos/keijiro/AIShader/subscription",
            "commits_url": "https://api.github.com/repos/keijiro/AIShader/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/keijiro/AIShader/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/keijiro/AIShader/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/keijiro/AIShader/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/keijiro/AIShader/contents/{+path}",
            "compare_url": "https://api.github.com/repos/keijiro/AIShader/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/keijiro/AIShader/merges",
            "archive_url": "https://api.github.com/repos/keijiro/AIShader/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/keijiro/AIShader/downloads",
            "issues_url": "https://api.github.com/repos/keijiro/AIShader/issues{/number}",
            "pulls_url": "https://api.github.com/repos/keijiro/AIShader/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/keijiro/AIShader/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/keijiro/AIShader/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/keijiro/AIShader/labels{/name}",
            "releases_url": "https://api.github.com/repos/keijiro/AIShader/releases{/id}",
            "deployments_url": "https://api.github.com/repos/keijiro/AIShader/deployments",
            "created_at": "2023-03-05T12:18:33Z",
            "updated_at": "2023-05-16T03:13:30Z",
            "pushed_at": "2023-03-22T11:39:58Z",
            "git_url": "git://github.com/keijiro/AIShader.git",
            "ssh_url": "git@github.com:keijiro/AIShader.git",
            "clone_url": "https://github.com/keijiro/AIShader.git",
            "svn_url": "https://github.com/keijiro/AIShader",
            "homepage": "",
            "size": 45,
            "stargazers_count": 1906,
            "watchers_count": 1906,
            "language": "C#",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "has_discussions": false,
            "forks_count": 187,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": null,
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [],
            "visibility": "public",
            "forks": 187,
            "open_issues": 1,
            "watchers": 1906,
            "default_branch": "main"
          }
        ];

       this._store.dispatch(getUserRepositoriesListSuccess({ data: list }));

        return [];
      })
    )
  );

  fetchUserRepositoriesListTotal$ = createEffect(() =>
    this._actions$.pipe(
      ofType(AppActions.FetchUserRepositoriesListTotal),
      switchMap(({ login }) =>
        this._usersService.getUser(login)
      ),
      map(({ public_repos }) => {
        
        return getUserRepositoriesListSuccess({ total: public_repos });
      })
    )
  );
}
